# Generated by Django 4.2.18 on 2025-02-11 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulo', '0003_alter_titulo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Id do Instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Rg do Intrutor', max_length=15)),
                ('nome', models.CharField(help_text='nome do instrutor', max_length=70)),
                ('dataNascimento', models.DateField(blank=True, help_text='data de nascimento do instrutor', null=True)),
                ('telefone', models.CharField(help_text='Numero de telefone do instrutor', max_length=9)),
                ('ddd', models.CharField(help_text='informe o ddd do instrutor', max_length=9)),
                ('codigo_titulo', models.ForeignKey(blank=True, db_column='titulo_codigo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulo.titulo')),
            ],
        ),
    ]
