# Generated by Django 4.2.18 on 2025-02-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Código do Aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do aluno', max_length=70)),
                ('dataInicial', models.DateField(help_text='Data inicial do Aluno')),
                ('dataFinal', models.DateField(help_text='Data Final do Aluno')),
            ],
        ),
    ]
