# Generated by Django 4.2.18 on 2025-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataFinal',
            field=models.DateField(blank=True, help_text='Data Final do Aluno', null=True),
        ),
    ]
